import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

// Rebuild using an unpacked zipcodes@8.0.0 npm package:
// node scripts/generate-zips.mjs /path/to/zipcodes/package
// The package is a build-time data source; the app needs no runtime dependency.
const packageDirectory = process.argv[2];
if (!packageDirectory) {
  throw new Error('Pass the directory containing the unpacked zipcodes@8.0.0 package.');
}

const sourceDirectory = resolve(packageDirectory);
const require = createRequire(import.meta.url);
const source = require(resolve(sourceDirectory, 'lib/codes.js'));
const metadata = JSON.parse(await readFile(resolve(sourceDirectory, 'package.json'), 'utf8'));
if (metadata.name !== 'zipcodes' || metadata.version !== '8.0.0') {
  throw new Error('Use zipcodes@8.0.0 so regeneration preserves the reviewed source dataset.');
}

const stateCodes = 'AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' ');
const zipLocations = Object.fromEntries(stateCodes.map(code => [code, []]));
const seen = new Set();
let excluded = 0;
for (const row of Object.values(source.codes)) {
  if (!Object.hasOwn(zipLocations, row.state)) continue;
  if (row.country !== 'US' || !/^\d{5}$/.test(row.zip) || !row.city ||
      !Number.isFinite(row.longitude) || !Number.isFinite(row.latitude) ||
      row.latitude < 18 || row.latitude > 72 || Math.abs(row.longitude) > 180) {
    excluded += 1;
    continue;
  }
  // NY 10200 has an east-positive coordinate in the source, placing it in Asia.
  // HI 96898 belongs to Wake Island, outside Hawaii's geographic state boundary.
  // Exclude these records rather than inventing replacement coordinates.
  if ((row.state !== 'AK' && row.longitude > -60) || seen.has(row.zip)) {
    excluded += 1;
    continue;
  }
  seen.add(row.zip);
  zipLocations[row.state].push([row.zip, row.city, row.longitude, row.latitude]);
}

for (const [code, rows] of Object.entries(zipLocations)) {
  if (!rows.length) throw new Error(`Source contains no usable ZIP locations for ${code}.`);
  rows.sort((a, b) => a[0].localeCompare(b[0], 'en'));
}

const sourceLicense = await readFile(resolve(sourceDirectory, 'LICENSE'), 'utf8');
const header = `/*
 * ZIP centroid locations from zipcodes@8.0.0 (Dav Glass).
 * Package: https://www.npmjs.com/package/zipcodes/v/8.0.0
 * Source: https://github.com/davglass/zipcodes
 * US postal data: http://federalgovernmentzipcodes.us/
 * Coordinate data: GeoNames, https://www.geonames.org/ (CC BY attribution).
 * Arrays contain [ZIP as a five-character string, city, longitude, latitude].
 * These are postal centroid estimates, not ZIP boundary polygons or live USPS data.
 * Includes ${seen.size.toLocaleString('en-US')} records in all 50 states; ${excluded} unusable/outside-state records excluded.
 * Generated by scripts/generate-zips.mjs. Do not hand-edit the dataset.
 *
${sourceLicense.split('\n').map(line => ` * ${line}`).join('\n')}
 */\n`;
const serialized = stateCodes.map(code => `  ${code}: ${JSON.stringify(zipLocations[code])}`).join(',\n');
const destination = new URL('../src/zip-data.js', import.meta.url);
await writeFile(destination, `${header}export const zipLocations = {\n${serialized}\n};\nexport const zipLocationCount = ${seen.size};\n`);
console.log(`Generated ${seen.size} ZIP locations across ${stateCodes.length} states (${excluded} excluded).`);
