"""Generate shortcut ZIP intersections from projected Census place polygons.

Requires Shapely; input cities have their TIGER polygons projected with
projectStatePoint from src/us-map.js, using the same projection as ZIP paths.
Usage: python scripts/generate-city-shortcuts.py PROJECTED_CITIES.json
"""
import json, re, sys
from pathlib import Path
from shapely.geometry import Polygon, Point, shape
from shapely.ops import unary_union

root = Path(__file__).resolve().parent.parent
source = json.loads(Path(sys.argv[1]).read_text())
result = {}
for state, cities in source['cities'].items():
    areas = json.loads((root / 'src/zip-boundaries' / (state+'.json')).read_text())['areas']
    polygons = {}
    for area in areas:
        # SVG paths use even-odd fill: symmetric differences retain holes.
        polygon = Polygon()
        for ring in re.findall(r'M([^Z]+)Z', area['path']):
            pairs = re.findall(r'(-?[\d.]+),(-?[\d.]+)', ring)
            if len(pairs) >= 3:
                polygon = polygon.symmetric_difference(Polygon([(float(x),float(y)) for x,y in pairs]).buffer(0))
        polygons[area['zip']] = polygon
    result[state] = []
    centers = {area['zip']:Point(area['center']) for area in areas}
    for city in cities:
        place = shape(city['geometry']).buffer(0)
        intersections = [(zip, poly.intersection(place)) for zip, poly in polygons.items() if poly.intersects(place)]
        intersections = [(zip, poly) for zip, poly in intersections if poly.area > .005]
        if not intersections:
            raise ValueError('No mapped ZIP areas for '+city['name']+', '+state)
        # Ignore tiny border/water slivers that would highlight unrelated ZIPs.
        local = [(zip,poly) for zip,poly in intersections
                 if place.covers(centers[zip]) or poly.area / polygons[zip].area >= .25]
        intersections = local or [max(intersections,key=lambda row:row[1].area)]
        x0,y0,x1,y1 = unary_union([poly for _,poly in intersections]).bounds
        width = min(960,max(12,(x1-x0)*1.25,(y1-y0)*960/600*1.25))
        result[state].append({'id':city['id'],'name':city['name'],'population':city['pop'],
                              'zips':sorted(zip for zip,_ in intersections),
                              'view':[round((x0+x1-width)/2,4),round((y0+y1-width*600/960)/2,4),round(width,4),round(width*600/960,4)]})
    print(state+': '+', '.join(c['name']+' ('+str(len(c['zips']))+')' for c in result[state]),flush=True)
metadata = {'populationSource':'Census ACS 2020–2024 B01003 via Census Reporter',
            'placeBoundaries':'Census TIGER 2024 via Census Reporter',
            'zipBoundaries':'Census ZCTA 2010',
            'sourceUrl':'https://api.censusreporter.org/1.0/data/show/acs2024_5yr',
            'geometryUrl':'https://api.censusreporter.org/1.0/geo/show/tiger2024',
            'retrievedDate':'2026-10-10',
            'method':'Five largest Census places per state, including census-designated places. Highlight ZIP areas with a mapped center inside the place or at least 25% area overlap. If none qualify, use the greatest area overlap. The view fits ZIP/place intersections, excluding tiny border/water slivers and offshore areas without mapped ZIPs.'}
(root/'src/city-shortcuts.js').write_text('// Generated by scripts/generate-city-shortcuts.py\nexport const cityShortcutSource = '+json.dumps(metadata)+';\nexport const stateCities = '+json.dumps(result,separators=(',',':'))+';\n')
